### ISSUE TITLE
Does it work on Linux?

### ISSUE THREAD

**Issue by voland62** [theloneplant/blender-spritesheets#10]
If no, could you mention this in the docs.
Thx.

**Comment by timmythetiny** [comment]
We would just need to compile the assembler program on Linux. This hasn't been done but could be done fairly easy.

**Comment by geoffsutcliffe** [comment]
FYI - I was able to build this assembler fine by running cargo build in the assembler directory. The plugin then worked with this executable.

**Comment by timmythetiny** [comment]
@geoffsutcliffe Would you be able to submit a pull request with the Linux binary?

**Comment by geoffsutcliffe** [comment]
Yep will do. I'll update the RenderSpriteSheet.py too, with windows/mac/linux exe names if you like?

**Comment by timmythetiny** [comment]
That would be much appreciated. Thank you kind sir.

**Comment by timmythetiny** [comment]
Merged in #11. Thanks for your contribution.
