### ISSUE TITLE
Unity importer splits spritesheet incorrectly

### ISSUE THREAD

**Issue by BenoitCavrois** [theloneplant/blender-spritesheets#13]
Hello, 

when I use the plugin in Blender to get the sprite sheet and try to parse it into my Unity project, Unity try to slice the sheet to make all the sprites but the split order is incorrect. Some sprites are not selected. 
Do you know why is this happening?

Thank you. 

![Capture](https://user-images.githubusercontent.com/23339261/102209583-3ef0fd80-3ed1-11eb-8454-58fa32310bdf.PNG)

**Comment by tim-harding** [comment]
That'll be a bug. I'll see if I can reproduce this.

**Comment by BenoitCavrois** [comment]
Hello, have you been able to reproduce the bug? I tried to understand the problem and I still truggle with it. 
In addition, the sprite sheet imported to Unity does create an animation but it is empty with no frames in it.

**Comment by theloneplant** [comment]
I was able to reproduce this and just pushed a quick fix for it, let me know you're still having issues!
