### ISSUE TITLE
Spritesheet creator doesn't render the last animation frame

### ISSUE THREAD

**Issue by vicvillalobos** [theloneplant/blender-spritesheets#8]
Hi, I was testing your script and figured out the following:

When rendering one or more animations (using a rigged character, for example), the resulting spritesheet doesn't show the last frame of each animation.

**To reproduce the problem:**

- Install blender-spritesheets add-on
- Create/Import rigged character, create an animation using a few frames (I used 6).
- Press Render Sprite Sheet

**Expectation:**
All 6 frames are rendered correctly

**What's actually happening:**
Only the first 5 frames are rendered correctly. The last one is omitted.

**Workaround:**
Create an extra frame for each animation, making that the ignored frame.

**Blender version:**
Issue tested in 2.80 Beta & 2.82

**Comment by timmythetiny** [comment]
Closed with commit b8b0c7b
